/**
 * bdf-writer.ts — Nastran BDF/NAS file exporter
 *
 * Writes small-field format (most portable across Nastran flavors):
 * - GRID cards (8-char field node coordinates)
 * - Element cards (CQUAD4, CTRIA3, CTETRA, CHEXA, CPENTA, CBAR)
 * - PSHELL/PSOLID property cards
 */

import { MeshModel, MeshElement } from '../core/mesh-model';
import { ElementShape } from '../core/element-types';
import { MeshWriter, WriteOptions, registerWriter } from './parser-registry';

// ─── Formatting Helpers ──────────────────────────────────────────────────────

/** Format a value into a Nastran small-field (8 characters, right-aligned) */
function field8(value: string | number): string {
  let s: string;
  if (typeof value === 'number') {
    if (Number.isInteger(value)) {
      s = value.toString();
    } else {
      // Format float to fit in 8 chars
      s = formatNastranFloat(value, 8);
    }
  } else {
    s = value;
  }
  // Right-align in 8 characters
  if (s.length > 8) s = s.substring(0, 8);
  return s.length < 8 ? ' '.repeat(8 - s.length) + s : s;
}

/** Format a float to fit in the given width using Nastran conventions */
function formatNastranFloat(value: number, width: number): string {
  if (value === 0) return '0.0'.padStart(width);

  // Try fixed notation first
  for (let d = width - 3; d >= 1; d--) {
    const s = value.toFixed(d);
    if (s.length <= width) return s;
  }

  // Fall back to exponential (Nastran shorthand: "1.23+4" instead of "1.23E+4")
  const exp = value.toExponential(width - 6);
  // Replace "e+" with "+" and "e-" with "-"
  const shorthand = exp.replace(/e\+?/, (match) => match.includes('-') ? '-' : '+');
  if (shorthand.length <= width) return shorthand;

  return value.toExponential(1);
}

/** Get the Nastran card name for a canonical element shape */
function getNastranCardName(shape: ElementShape): string {
  switch (shape) {
    case ElementShape.TRI3: return 'CTRIA3';
    case ElementShape.TRI6: return 'CTRIA6';
    case ElementShape.QUAD4: return 'CQUAD4';
    case ElementShape.QUAD8: return 'CQUAD8';
    case ElementShape.TET4:
    case ElementShape.TET10: return 'CTETRA';
    case ElementShape.HEX8:
    case ElementShape.HEX20: return 'CHEXA';
    case ElementShape.WEDGE6:
    case ElementShape.WEDGE15: return 'CPENTA';
    case ElementShape.BEAM2: return 'CBAR';
    case ElementShape.BEAM3: return 'CBEAM';
    default: return 'CQUAD4';
  }
}

// ─── BDF Writer Implementation ──────────────────────────────────────────────

function writeBdf(model: MeshModel, options?: WriteOptions): string {
  const lines: string[] = [];

  // ─── Header ────────────────────────────────────────────────────────────
  if (options?.includeHeader !== false) {
    lines.push(`$ Nastran Bulk Data File`);
    lines.push(`$ Generated by MeshMend AI`);
    if (options?.title || model.metadata.title) {
      lines.push(`$ Title: ${options?.title || model.metadata.title}`);
    }
    lines.push('$');
    lines.push('BEGIN BULK');
  }

  // ─── Property Cards ────────────────────────────────────────────────────
  const propMap = model.metadata.formatExtras['propertyMap'] as
    Record<string, { type: string; matId: number }> | undefined;

  if (propMap) {
    lines.push('$');
    lines.push('$ PROPERTY CARDS');
    lines.push('$');
    for (const [pid, prop] of Object.entries(propMap)) {
      if (prop.type === 'PSHELL') {
        // PSHELL: PID, MID1, T, MID2, 12I/T**3, MID3, TS/T, NSM
        lines.push(
          field8('PSHELL') + field8(parseInt(pid)) + field8(prop.matId) +
          field8(1.0) // default thickness
        );
      } else if (prop.type === 'PSOLID') {
        lines.push(
          field8('PSOLID') + field8(parseInt(pid)) + field8(prop.matId)
        );
      } else {
        lines.push(
          field8(prop.type) + field8(parseInt(pid)) + field8(prop.matId)
        );
      }
    }
  } else {
    // Generate minimal property cards from elements
    const usedPids = new Set<number>();
    for (const elem of model.elements) {
      usedPids.add(elem.attrs.propertyId || 1);
    }
    if (usedPids.size > 0) {
      lines.push('$');
      lines.push('$ PROPERTY CARDS');
      lines.push('$');
      for (const pid of usedPids) {
        lines.push(field8('PSHELL') + field8(pid) + field8(1) + field8(1.0));
      }
    }
  }

  // ─── GRID Cards ────────────────────────────────────────────────────────
  const nodeIds = model.nodes.ids.sort((a, b) => a - b);
  lines.push('$');
  lines.push('$ GRID CARDS');
  lines.push('$');

  for (const nodeId of nodeIds) {
    const xyz = model.nodes.getXYZ(nodeId);
    if (!xyz) continue;
    const [x, y, z] = xyz;

    // GRID card: GRID, ID, CP, X1, X2, X3, CD, PS, SEID
    lines.push(
      field8('GRID') +
      field8(nodeId) +
      field8('') +     // CP (blank = global)
      field8(x) +
      field8(y) +
      field8(z)
    );
  }

  // ─── Element Cards ─────────────────────────────────────────────────────
  const allElements: MeshElement[] = [];
  for (const elem of model.elements) {
    allElements.push(elem);
  }
  allElements.sort((a, b) => a.id - b.id);

  lines.push('$');
  lines.push('$ ELEMENT CARDS');
  lines.push('$');

  for (const elem of allElements) {
    const cardName = getNastranCardName(elem.shape);
    const pid = elem.attrs.propertyId || 1;

    // Build all fields: CardName, EID, PID, G1, G2, G3, ...
    const allFields = [cardName, elem.id, pid, ...elem.nodeIds];

    // Small field: 10 fields per line (including card name)
    // First line: fields 0-9
    let line = '';
    for (let f = 0; f < Math.min(allFields.length, 10); f++) {
      line += field8(allFields[f]);
    }
    lines.push(line);

    // Continuation lines if >10 fields
    if (allFields.length > 10) {
      let pos = 10;
      let contIdx = 1;
      while (pos < allFields.length) {
        let contLine = field8('+' + contIdx.toString().padStart(7)); // continuation label
        const endPos = Math.min(pos + 8, allFields.length);
        for (let f = pos; f < endPos; f++) {
          contLine += field8(allFields[f]);
        }
        lines.push(contLine);
        pos += 8;
        contIdx++;
      }
    }
  }

  // ─── Footer ────────────────────────────────────────────────────────────
  lines.push('$');
  lines.push('ENDDATA');
  lines.push('');

  return lines.join('\n');
}

// ─── Register Writer ─────────────────────────────────────────────────────────

export const bdfWriter: MeshWriter = {
  formatName: 'Nastran BDF',
  defaultExtension: '.bdf',
  write: writeBdf,
};

registerWriter(bdfWriter);
