/**
 * cdb-writer.ts — ANSYS MAPDL .cdb (Coded Database) exporter
 *
 * Writes the blocked format that can be read by MAPDL CDREAD:
 * - ET commands (element type definitions)
 * - NBLOCK with Fortran format
 * - EBLOCK with full 19-field attribute records
 * - CMBLOCK for component/named selection groups
 */

import { MeshModel, MeshElement } from '../core/mesh-model';
import { MeshWriter, WriteOptions, registerWriter } from './parser-registry';

// ─── Formatting Helpers ──────────────────────────────────────────────────────

/** Pad a number to fixed width (right-aligned integer) */
function padInt(value: number, width: number): string {
  const s = Math.round(value).toString();
  return s.length >= width ? s : ' '.repeat(width - s.length) + s;
}

/** Format a float in Fortran E notation with fixed width */
function padFloat(value: number, width: number, decimals: number): string {
  // Use exponential notation matching Fortran format
  const s = value.toExponential(decimals);
  // Pad or trim to fit width
  return s.length >= width ? s : ' '.repeat(width - s.length) + s;
}

// ─── CDB Writer Implementation ──────────────────────────────────────────────

function writeCdb(model: MeshModel, options?: WriteOptions): string {
  const lines: string[] = [];
  const precision = options?.precision ?? 13;

  // ─── Header ────────────────────────────────────────────────────────────
  if (options?.includeHeader !== false) {
    lines.push('/COM,ANSYS MAPDL CDB FILE');
    lines.push(`/COM,Generated by MeshMend AI`);
    if (options?.title || model.metadata.title) {
      lines.push(`/TITLE,${options?.title || model.metadata.title}`);
    }
    lines.push('/PREP7');
    lines.push('');
  }

  // ─── ET Definitions ────────────────────────────────────────────────────
  const etDefs = model.metadata.formatExtras['etDefinitions'] as
    Record<string, { typeRef: number; typeId: number; keyopts: Record<number, number> }> | undefined;

  if (etDefs) {
    for (const def of Object.values(etDefs)) {
      lines.push(`ET,${def.typeRef},${def.typeId}`);
      if (def.keyopts) {
        for (const [knum, kval] of Object.entries(def.keyopts)) {
          lines.push(`KEYOPT,${def.typeRef},${knum},${kval}`);
        }
      }
    }
    lines.push('');
  } else {
    // Generate ET definitions from elements
    const typeRefs = new Set<number>();
    for (const elem of model.elements) {
      typeRefs.add(elem.attrs.formatTypeRef);
    }
    for (const typeRef of typeRefs) {
      if (typeRef > 0) {
        lines.push(`ET,${typeRef},${typeRef}`);
      }
    }
    if (typeRefs.size > 0) lines.push('');
  }

  // ─── NBLOCK ────────────────────────────────────────────────────────────
  const nodeIds = model.nodes.ids.sort((a, b) => a - b);
  const maxNodeId = nodeIds.length > 0 ? nodeIds[nodeIds.length - 1] : 0;

  lines.push(`NBLOCK,6,SOLID,${maxNodeId},${nodeIds.length}`);
  lines.push(`(3i9,6e${precision + 7}.${precision})`);

  for (const nodeId of nodeIds) {
    const xyz = model.nodes.getXYZ(nodeId);
    if (!xyz) continue;
    const [x, y, z] = xyz;
    // Format: nodeId(i9), solidRef(i9), lineRef(i9), x(eW.D), y(eW.D), z(eW.D)
    const fieldWidth = precision + 7;
    const line =
      padInt(nodeId, 9) +
      padInt(0, 9) +
      padInt(0, 9) +
      padFloat(x, fieldWidth, precision) +
      padFloat(y, fieldWidth, precision) +
      padFloat(z, fieldWidth, precision);
    lines.push(line);
  }
  lines.push('N,R5.3,LOC,-1,');
  lines.push('');

  // ─── EBLOCK ────────────────────────────────────────────────────────────
  // Group elements by type reference for cleaner output
  const allElements: MeshElement[] = [];
  for (const elem of model.elements) {
    allElements.push(elem);
  }
  allElements.sort((a, b) => a.id - b.id);

  if (allElements.length > 0) {
    const maxNodes = Math.max(...allElements.map((e) => e.nodeIds.length));
    const numFields = 11 + maxNodes; // 11 header fields + node fields
    lines.push(`EBLOCK,19,SOLID,${allElements[allElements.length - 1].id},${allElements.length}`);

    // Format string: 19 integer fields of width 9
    lines.push(`(19i9)`);

    for (const elem of allElements) {
      // 19-field EBLOCK line:
      // MAT, TYPE, REAL, SECNUM, ESYS, DEATH, SOLIDM, SHAPE, NUMNODE, notused, ELNUM, nodes...
      const numNodes = elem.nodeIds.length;
      const fields = [
        elem.attrs.materialId,           // [0] MAT
        elem.attrs.formatTypeRef,        // [1] TYPE
        elem.attrs.realConstantId,       // [2] REAL
        elem.attrs.sectionId,            // [3] SECNUM
        elem.attrs.coordinateSystemId,   // [4] ESYS
        0,                                // [5] DEATH (0 = alive)
        0,                                // [6] SOLIDMODEL ref
        0,                                // [7] SHAPE
        numNodes,                         // [8] NUMNODE
        0,                                // [9] not used
        elem.id,                          // [10] ELNUM
        ...elem.nodeIds,                  // [11..] node IDs
      ];

      // Pad to 19 fields minimum
      while (fields.length < 19) fields.push(0);

      // First line: up to 19 fields
      let line = fields.slice(0, 19).map((v) => padInt(v, 9)).join('');
      lines.push(line);

      // Continuation line if >8 nodes (fields beyond 19)
      if (fields.length > 19) {
        line = fields.slice(19).map((v) => padInt(v, 9)).join('');
        lines.push(line);
      }
    }
    lines.push(padInt(-1, 9));
    lines.push('');
  }

  // ─── CMBLOCK (Component Blocks) ────────────────────────────────────────
  for (const [name, comp] of model.components) {
    const compType = comp.originalType || 'ELEMENT';
    const ids =
      compType === 'NODE'
        ? Array.from(comp.nodeIds).sort((a, b) => a - b)
        : Array.from(comp.elementIds).sort((a, b) => a - b);

    if (ids.length === 0) continue;

    lines.push(`CMBLOCK,${name},${compType},${ids.length}`);
    lines.push('(8i10)');

    // Write IDs in rows of 8
    for (let j = 0; j < ids.length; j += 8) {
      const chunk = ids.slice(j, j + 8);
      lines.push(chunk.map((id) => padInt(id, 10)).join(''));
    }
    lines.push('');
  }

  // ─── Footer ────────────────────────────────────────────────────────────
  lines.push('FINISH');
  lines.push('');

  return lines.join('\n');
}

// ─── Register Writer ─────────────────────────────────────────────────────────

export const cdbWriter: MeshWriter = {
  formatName: 'ANSYS CDB',
  defaultExtension: '.cdb',
  write: writeCdb,
};

registerWriter(cdbWriter);
