/**
 * inp-writer.ts — Abaqus .inp file exporter
 *
 * Writes valid Abaqus input files re-importable by Abaqus/CAE:
 * - *HEADING
 * - *NODE
 * - *ELEMENT, TYPE=xxx (grouped by element type)
 * - *ELSET (component groups)
 * - *NSET (node groups)
 */

import { MeshModel, MeshElement } from '../core/mesh-model';
import { ElementShape, ABAQUS_ELEMENT_MAP } from '../core/element-types';
import { MeshWriter, WriteOptions, registerWriter } from './parser-registry';

// ─── Reverse Mapping: Canonical Shape → Abaqus Type String ───────────────────

const SHAPE_TO_ABAQUS: Record<string, string> = {};
// Build reverse map
for (const [abaqusType, shape] of Object.entries(ABAQUS_ELEMENT_MAP)) {
  if (!SHAPE_TO_ABAQUS[shape]) {
    SHAPE_TO_ABAQUS[shape] = abaqusType;
  }
}

function getAbaqusType(elem: MeshElement, formatExtras: Record<string, unknown>): string {
  // Try to use the original Abaqus type if preserved
  const elementTypes = formatExtras['elementTypes'] as Record<string, string> | undefined;
  if (elementTypes && elementTypes[elem.id.toString()]) {
    return elementTypes[elem.id.toString()];
  }
  return SHAPE_TO_ABAQUS[elem.shape] || 'C3D8';
}

// ─── INP Writer Implementation ──────────────────────────────────────────────

function writeInp(model: MeshModel, options?: WriteOptions): string {
  const lines: string[] = [];
  const precision = options?.precision ?? 10;

  // ─── Heading ───────────────────────────────────────────────────────────
  lines.push('*HEADING');
  lines.push(options?.title || model.metadata.title || 'Generated by MeshMend AI');

  // ─── Nodes ─────────────────────────────────────────────────────────────
  const nodeIds = model.nodes.ids.sort((a, b) => a - b);
  lines.push('**');
  lines.push('** NODES');
  lines.push('**');
  lines.push('*NODE');

  for (const nodeId of nodeIds) {
    const xyz = model.nodes.getXYZ(nodeId);
    if (!xyz) continue;
    const [x, y, z] = xyz;
    lines.push(`${nodeId}, ${x.toPrecision(precision)}, ${y.toPrecision(precision)}, ${z.toPrecision(precision)}`);
  }

  // ─── Elements (grouped by Abaqus type) ─────────────────────────────────
  // Group elements by their Abaqus type string
  const typeGroups = new Map<string, MeshElement[]>();
  for (const elem of model.elements) {
    const abaqusType = getAbaqusType(elem, model.metadata.formatExtras);
    const group = typeGroups.get(abaqusType);
    if (group) {
      group.push(elem);
    } else {
      typeGroups.set(abaqusType, [elem]);
    }
  }

  for (const [abaqusType, elements] of typeGroups) {
    elements.sort((a, b) => a.id - b.id);

    // Group by elset/component
    const elsetGroups = new Map<string, MeshElement[]>();
    for (const elem of elements) {
      const setName = elem.componentName || '';
      const group = elsetGroups.get(setName);
      if (group) {
        group.push(elem);
      } else {
        elsetGroups.set(setName, [elem]);
      }
    }

    for (const [elsetName, setElements] of elsetGroups) {
      lines.push('**');
      let header = `*ELEMENT, TYPE=${abaqusType}`;
      if (elsetName) {
        header += `, ELSET=${elsetName}`;
      }
      lines.push(header);

      for (const elem of setElements) {
        // Element connectivity line: elemId, n1, n2, n3, ...
        // Break into lines of max 16 entries (Abaqus convention)
        const allVals = [elem.id, ...elem.nodeIds];
        const maxPerLine = 16;

        if (allVals.length <= maxPerLine) {
          lines.push(allVals.join(', '));
        } else {
          // First line
          lines.push(allVals.slice(0, maxPerLine).join(', ') + ',');
          // Continuation lines
          let pos = maxPerLine;
          while (pos < allVals.length) {
            const chunk = allVals.slice(pos, pos + maxPerLine);
            const isLast = pos + maxPerLine >= allVals.length;
            lines.push(chunk.join(', ') + (isLast ? '' : ','));
            pos += maxPerLine;
          }
        }
      }
    }
  }

  // ─── Element Sets (components that aren't already ELSET on *ELEMENT) ────
  for (const [name, comp] of model.components) {
    if (comp.originalType === 'ELEMENT' || comp.elementIds.size > 0) {
      const ids = Array.from(comp.elementIds).sort((a, b) => a - b);
      if (ids.length === 0) continue;

      lines.push('**');
      lines.push(`*ELSET, ELSET=${name}`);

      // Write IDs, max 16 per line
      for (let j = 0; j < ids.length; j += 16) {
        const chunk = ids.slice(j, j + 16);
        const isLast = j + 16 >= ids.length;
        lines.push(chunk.join(', ') + (isLast ? '' : ','));
      }
    }
  }

  // ─── Node Sets ─────────────────────────────────────────────────────────
  for (const [name, comp] of model.components) {
    if (comp.originalType === 'NODE' || (comp.nodeIds.size > 0 && comp.elementIds.size === 0)) {
      const ids = Array.from(comp.nodeIds).sort((a, b) => a - b);
      if (ids.length === 0) continue;

      lines.push('**');
      lines.push(`*NSET, NSET=${name}`);

      for (let j = 0; j < ids.length; j += 16) {
        const chunk = ids.slice(j, j + 16);
        const isLast = j + 16 >= ids.length;
        lines.push(chunk.join(', ') + (isLast ? '' : ','));
      }
    }
  }

  // ─── Section Assignments ───────────────────────────────────────────────
  const sectionAssignments = model.metadata.formatExtras['sectionAssignments'] as
    Array<{ elset: string; material: string; type: string }> | undefined;

  if (sectionAssignments) {
    for (const sa of sectionAssignments) {
      lines.push('**');
      lines.push(`*${sa.type}, ELSET=${sa.elset}, MATERIAL=${sa.material}`);
      lines.push(''); // Blank data line (section thickness etc. would go here)
    }
  }

  lines.push('**');
  lines.push('** END OF MODEL DATA');
  lines.push('**');
  lines.push('');

  return lines.join('\n');
}

// ─── Register Writer ─────────────────────────────────────────────────────────

export const inpWriter: MeshWriter = {
  formatName: 'Abaqus INP',
  defaultExtension: '.inp',
  write: writeInp,
};

registerWriter(inpWriter);
